# Site settings
title: Hiwr
email: contact@worldline.com
description: > # this means to ignore newlines until "baseurl:"
  Hiwr is an OpenSource robot created by Worldline. Based on an Olimex A13-OLinuXino, it runs linux, ROS and free Softwares
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hiwr.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  hiwr

# Build settings
markdown: kramdown

kramdown:
  input: GFM
